### ISSUE TITLE
React Hooks

### ISSUE THREAD

**Issue by Stan015** [Oluwasetemi/react-note#12]
- What is state
- Introduction to React Hooks  
- Basic Hooks: "useState", "useEffect"  
- Managing Side Effects with "useEffect"  
- Complex state (Right way to update objects and arrays in state) - Mutation
- Immutability
- Rules of Hooks

 Use the hook.md file or create one if it doesn't exist yet.

**Comment by Olubebe** [comment]
@Oluwasetemi I want to work on this issue

**Comment by Oluwasetemi** [comment]
Cc @Stan015 and @victorvictoria-maker are the coordinator. 

It's should be the same approach. Come up with the content and they will be reviewers.

**Comment by Stan015** [comment]
Hello @Olubebe 👋,
We look forward to your PR soon on this issue.

**Comment by Olubebe** [comment]
Will send a pr soon
